language: python
services:
  - postgresql
python:
  - 3.6
install:
  - pip install -r requirements/prod.txt
before_script:
  - cp ahmia/ahmia/settings/example.env ahmia/ahmia/settings/.env
  - python ahmia/manage.py migrate
script:
  - python ahmia/manage.py test
