language: python
services:
  - postgresql
python:
  - 3.6
before_install:
  # You could put elasticsearch in "services" but in order to specify version:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.4.0.deb
  - sudo service elasticsearch restart
install:
  - pip install -r requirements/prod.txt
before_script:
  - sleep 10  # give some time to ES to start
  - psql -c 'create database ahmiasite;' -U postgres
  - cd ahmia
  - cp ahmia/settings/example.env ahmia/settings/.env
  - python manage.py collectstatic --noinput -c
  - python manage.py migrate
script:
  - python manage.py test
